baseURL: "/"
title: Tommaso Sgrizzi
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Python projects
          url: /python_projects/
          weight: 4
        - name: Conferences
          url: /conferences/
          weight: 1
        #- name: Courses
        #  url: /courses/
        #  weight: 2
        #- name: Design
        #  url: /design/
        #  weight: 3
        #- name: Tags
        #  url: /tags/
        #  weight: 5
        #- name: Newsletter
        #  url: https://pmichaillat.substack.com
        #  weight: 4

params:
    description: "I am a PhD student in linguistics at IUSS Pavia."
    author: Tommaso Sgrizzi
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tommaso Sgrizzi
          subtitle: "Hi! I'm a PhD student in Linguistics at IUSS Pavia and a member of the [SOLE](https://www.universiteitleiden.nl/en/events/series/sole) board, working on the syntax and acquisition of specific infinitive-taking verbs (known as 'restructuring verbs') in Italian and other Romance languages. In my free time, you can find me drawing, taking photos of my friends, or playing music. Additionally, my recent dive into Python has allowed me to integrate programming with my research interests. Feel free to explore some of my initial projects on this site's dedicated page ✨"
          imageUrl: "tom.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tommaso Sgrizzi
          buttons:
            - name: Conferences
              url: /conferences/
            - name: Python projects
              url: /python_projects/
            #- name: Courses
            #  url: /courses/
            #- name: Design
            #  url: /design/
            #- name: Newsletter
             #  url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /tom_cv.pdf
        - name: Email
          url: mailto:tommaso.sgrizzi@iusspavia.it
        #- name: Location
        #  url: /location/
        #- name: Office Hours
        #  url: /officehours/
        - name: Academia
          url: https://www.iusspavia.it/en/contacts/tommaso-sgrizzi
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        #- name: GitHub
        #  url: https://github.com/pmichaillat?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Tommaso Sgrizzi"
      icon: /light-bulb.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
